### ISSUE TITLE
Type-Fehler FN_BauteileVorhanden 

### ISSUE THREAD

**Issue by Mr-DaGolle** [The-Uniques/Projekt-Bibo#12]
Bei Zeile 608 im Script : declare @istStk decimal(7,2), @rkStk decimal(7,2)
müsste da nicht als Typ int stehen, da in ROBOTERKOMPONENTEN - RKStueckzahl int ist und in LAGERBESTAND - IstStk auch int ist ???

**Comment by MarkusW95** [comment]
Ja stimmt, schau ich morgen nach und änder ich

**Comment by MarkusW95** [comment]
Ist erledigt
