### ISSUE TITLE
ER-Model Lückenhaft - Siehe Tabelle ROBOTER

### ISSUE THREAD

**Issue by The-Uniques** [The-Uniques/Projekt-Bibo#13]
Bitte Noch mal das ER Modell Überarbeiten und an die Aktuellen SQL Tables anpassen, hab es gerade anhand des eER-Models gemerkt .

Wäre schön, wenn ihr noch mal über das eER Modell schaut, bin mir nicht sicher ob das zu 100% passt.

**Comment by MarkusW95** [comment]
siehe Comment Issue #15

**Comment by The-Uniques** [comment]
Ich habe es jetzt angepasst an die Tabellen der Database
