### ISSUE TITLE
Datentypen RelationenModel

### ISSUE THREAD

**Issue by Mr-DaGolle** [The-Uniques/Projekt-Bibo#6]
Wie groß sollen die varchar Variablen für **BAUTEILE**->Bezeichnung, **ROBOTER**->Bezeichnung sein?
Die länge der Nachkommastelle decimal(7,2) reicht mit 2 Nachkommastellen?
Wo soll die **RoboterID** aus Tabelle **Roboter** beginnen ? Bei 0, oder 1000 oder 100000? #5 
[Relationales Modell.xlsx](https://github.com/The-Uniques/Projekt-Bibo/files/2131077/Relationales.Modell.xlsx)

**Comment by MarkusW95** [comment]
Bauteile-Bezeichnung varchar(80)
Roboter-Bezeichnung varchar(80)

2 Nachkommastellen reichen

RoboterID beginnend bei 0
